# These are the Drupal database settings
drupal_db_name: phanbook 
drupal_db_user: phanbook
drupal_db_password: phanbook
drupal_db_host: 127.0.0.1

# You shouldn't need to change this.
mysql_port: 3306

# The global variable file mongodb installation

# The chunksize for shards in MB
mongos_chunk_size: 1

# The port in which mongos server should listen on 
mongos_port: 8888

# The port for mongo config server
mongoc_port: 7777

mongod_port: 27017

# The directory prefix where the database files would be stored
mongodb_datadir_prefix: /data/

# The interface where the mongodb process should listen on.
# Defaults to the first interface. Change this to:
# 
#  iface: eth1
#
# ...to override.
# 
iface: '{{ ansible_default_ipv4.interface }}'

# The password for admin user
mongo_admin_pass: 123456

bindIp: 127.0.0.1